// Copyright 2022 Lucas Javaudin
//
// Licensed under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International
// https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode

//! Everything related to simulation parameters.
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use anyhow::{bail, Result};
use serde_derive::Deserialize;

use crate::learning::LearningModel;
use crate::network::road_network::parameters::RoadNetworkParameters;
use crate::units::Interval;

static PARAMETERS: OnceLock<Parameters> = OnceLock::new();

/// Initialize the global value of the parameters.
pub fn init(value: Parameters) -> Result<()> {
    if PARAMETERS.set(value).is_err() {
        bail!("Global parameters can be set only once");
    }
    Ok(())
}

/// Returns `true` if the global parameters are defined.
pub fn is_init() -> bool {
    PARAMETERS.get().is_some()
}

fn read_global() -> &'static Parameters {
    PARAMETERS.get().expect("Global parameters are not set")
}

pub(crate) fn input_files() -> &'static InputFiles {
    &read_global().input_files
}

pub(crate) fn output_directory() -> &'static Path {
    &read_global().output_directory
}

pub(crate) fn period() -> Interval {
    read_global().period
}

pub(crate) fn init_iteration_counter() -> u32 {
    read_global().init_iteration_counter
}

pub(crate) fn max_iterations() -> u32 {
    read_global().max_iterations
}

pub(crate) fn has_road_network_parameters() -> bool {
    read_global().road_network.is_some()
}

pub(crate) fn road_network() -> &'static RoadNetworkParameters {
    read_global()
        .road_network
        .as_ref()
        .expect("Road-network parameters are not set")
}

pub(crate) fn learning_model() -> &'static LearningModel {
    &read_global().learning_model
}

pub(crate) fn update_ratio() -> f64 {
    read_global().update_ratio
}

pub(crate) fn random_seed() -> Option<u64> {
    read_global().random_seed
}

pub(crate) fn nb_threads() -> usize {
    read_global().nb_threads
}

pub(crate) fn saving_format() -> SavingFormat {
    read_global().saving_format
}

pub(crate) fn only_compute_decisions() -> bool {
    read_global().only_compute_decisions
}

const fn default_iteration_counter() -> u32 {
    1
}

const fn default_update_ratio() -> f64 {
    1.0
}

/// Format to be used when saving files.
#[derive(Clone, Copy, Debug, Default, Deserialize)]
pub enum SavingFormat {
    /// Parquet files.
    #[default]
    Parquet,
    /// CSV files.
    CSV,
}

impl SavingFormat {
    pub(crate) fn extension(&self) -> String {
        match self {
            Self::Parquet => "parquet".into(),
            Self::CSV => "csv".into(),
        }
    }
}

/// Struct to store all the input file paths.
#[derive(Clone, Debug, Default, Deserialize)]
pub struct InputFiles {
    pub(crate) agents: PathBuf,
    pub(crate) alternatives: PathBuf,
    #[serde(default)]
    pub(crate) trips: Option<PathBuf>,
    #[serde(default)]
    pub(crate) edges: Option<PathBuf>,
    #[serde(default)]
    pub(crate) vehicle_types: Option<PathBuf>,
    #[serde(default)]
    pub(crate) road_network_conditions: Option<PathBuf>,
}

/// Set of parameters used to control how a [Simulation](crate::simulation::Simulation) is run.
#[derive(Clone, Debug, Deserialize)]
pub struct Parameters {
    /// Paths to the input files.
    pub input_files: InputFiles,
    /// Path to the output directory.
    #[serde(default)]
    pub output_directory: PathBuf,
    /// Time interval used to restrict the travel-time functions of the edges.
    ///
    /// The departure-time intervals of the agents must be included in this interval.
    ///
    /// Agents can still travel on the network when the period is exceeded but the edges' travel
    /// times are no longer recorded.
    /// The departure time chosen by any agent must be such that the expected arrival time is
    /// earlier than the end of the period.
    pub period: Interval,
    /// Initial iteration counter to use for the simulation.
    ///
    /// This is useful when running a simulation "step-by-step" (i.e., the input is modified
    /// partially from one iteration to another) so that, for example, the coefficients for the
    /// learning model are correctly computed.
    #[serde(default = "default_iteration_counter")]
    pub init_iteration_counter: u32,
    /// Maximum number of iterations to be run (on top of the `init_iteration_counter`).
    #[serde(default = "default_iteration_counter")]
    pub max_iterations: u32,
    /// Set of parameters for the road network.
    pub road_network: Option<RoadNetworkParameters>,
    /// Learning model used to update the values between two iterations.
    #[serde(default)]
    pub learning_model: LearningModel,
    /// Share of agents that can update their pre-day choices at each iteration.
    #[serde(default = "default_update_ratio")]
    pub update_ratio: f64,
    /// Random seed used for all the draws.
    ///
    /// If `null`, the seed is generated by entropy.
    #[serde(default)]
    pub random_seed: Option<u64>,
    /// Number of threads to use for parallel tasks.
    ///
    /// Default (0) is to use all the threads of the CPU.
    #[serde(default)]
    pub nb_threads: usize,
    /// Format to use for saving the output files.
    #[serde(default)]
    pub saving_format: SavingFormat,
    /// If `true`, the simulation will compute the travel decisions for the first iteration, save
    /// them and stop immediately.
    #[serde(default)]
    pub only_compute_decisions: bool,
}

impl Default for Parameters {
    fn default() -> Self {
        Self {
            input_files: Default::default(),
            output_directory: Default::default(),
            period: Interval::new_unchecked(0.0, 3600.0 * 24.0),
            init_iteration_counter: 1,
            max_iterations: 1,
            road_network: Some(Default::default()),
            learning_model: Default::default(),
            update_ratio: 1.0,
            random_seed: None,
            nb_threads: 0,
            saving_format: Default::default(),
            only_compute_decisions: false,
        }
    }
}
